// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwNk92xBD6ntP8wivmVMlPKvZ1jFjiZkE',
    appId: '1:815499362927:web:62946c547f4f43a0b6439a',
    messagingSenderId: '815499362927',
    projectId: 'my-flutter-apps-d9f5b',
    authDomain: 'my-flutter-apps-d9f5b.firebaseapp.com',
    storageBucket: 'my-flutter-apps-d9f5b.appspot.com',
    measurementId: 'G-Y1T1H83G9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARdRAKB1TUeHBxcbaHfOlNw5094dNINws',
    appId: '1:815499362927:android:5dd20d3b98e61f04b6439a',
    messagingSenderId: '815499362927',
    projectId: 'my-flutter-apps-d9f5b',
    storageBucket: 'my-flutter-apps-d9f5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgUpIjNff9yRGzvJrZOwyVjLNhjNTYejI',
    appId: '1:815499362927:ios:67146f699c4bbef5b6439a',
    messagingSenderId: '815499362927',
    projectId: 'my-flutter-apps-d9f5b',
    storageBucket: 'my-flutter-apps-d9f5b.appspot.com',
    iosClientId: '815499362927-0qs2uvn7k2t9e2qim6giqtvpg3fidaba.apps.googleusercontent.com',
    iosBundleId: 'com.example.aapnaBazar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgUpIjNff9yRGzvJrZOwyVjLNhjNTYejI',
    appId: '1:815499362927:ios:67146f699c4bbef5b6439a',
    messagingSenderId: '815499362927',
    projectId: 'my-flutter-apps-d9f5b',
    storageBucket: 'my-flutter-apps-d9f5b.appspot.com',
    iosClientId: '815499362927-0qs2uvn7k2t9e2qim6giqtvpg3fidaba.apps.googleusercontent.com',
    iosBundleId: 'com.example.aapnaBazar',
  );
}
